### ISSUE TITLE
Bug report : The Advanced Backups config is in the root Minecraft folder

### ISSUE THREAD

**Issue by NielsPilgaard** [MommyHeather/AdvancedBackups#25]
**Describe the bug**
The Advanced Backups config is in the root Minecraft folder

**Expected behavior**
I was expecting it to be in the config folder, with all the other mod configs 😄

**Comment by MommyHeather** [comment]
Fair. Not sure why I had been fine with it being in the root folder, but it might have been worries related to the config folder not always being `config`? I'll change that though if you prefer

**Comment by MommyHeather** [comment]
Closing, complete in [0e01383](https://github.com/MommyHeather/AdvancedBackups/commit/0e0138335bfa74ea4afd9a9a629c6333e17604db)
