### ISSUE TITLE
Feature request : Shell restore script

### ISSUE THREAD

**Issue by NielsPilgaard** [MommyHeather/AdvancedBackups#26]
**Is your feature request related to a problem? Please describe.**
Currently Mac and Unix users will have to use commands to run the AB jar, which could be made easier.

**Describe the solution you'd like**
I would like a `.sh` script to be generated to run the jar, just like there's a bat.

**Additional context**
If you're not familiar with shell I think I can help :P

**Comment by MommyHeather** [comment]
A .sh script should already be generated if you are on linux. I did this - is it not working for you?

**Comment by MommyHeather** [comment]
Nah, I thought it'd be less confusing for the user if there were two scripts but only one was runnable.

**Comment by NielsPilgaard** [comment]
Agreed 👍
