### ISSUE TITLE
Running `/advancedbackups start` gives limited feedback

### ISSUE THREAD

**Issue by NielsPilgaard** [MommyHeather/AdvancedBackups#27]
I ran `/advancedbackups start` and the only output it gave was `Starting backup`. It would be nice for it to at the very least report when it finishes.

**Comment by MommyHeather** [comment]
Initial plan was to implement it as part of #23, but I *have* just thought of a better way I think so I'll look into that tonight

**Comment by MommyHeather** [comment]
Resolved in [30c74e0](https://github.com/MommyHeather/AdvancedBackups/commit/30c74e03ee48232162474d8a8399502c10f759a8). Will wait until next update to publish

**Comment by NielsPilgaard** [comment]
Thaaank you

**Comment by NielsPilgaard** [comment]
> Will wait until next update to publish

Next update of what? 😅

**Comment by MommyHeather** [comment]
> > Will wait until next update to publish
> 
> Next update of what? 😅

Meant I'd release one update with all these issues fixed at once, rather than pushing an update just for the command change haha
