### ISSUE TITLE
Bug report : Cannot use CLI tool to restore world

### ISSUE THREAD

**Issue by NielsPilgaard** [MommyHeather/AdvancedBackups#29]
**Describe the bug**
While testing AB, I went into my singleplayer world "New World". I have 2, the other is called "Creative"
I ran all AB commands, including start and force-backup. This produced 2 full differential backups.
I then left the world, and deleted the contents of the save, but not the "New World" folder within the saves folder.

I then ran the restore.bat script to execute the jar. Here's a screenshot of my interaction with the CLI:
![image](https://github.com/MommyHeather/AdvancedBackups/assets/21295394/4572b433-dc49-44cf-977d-f96db7dc5a19)

**Expected behavior**
For me to be able to restore my world with the CLI tool.

**Screenshots**

**Versioning (please complete the following information):**
 - OS: [e.g. Debian]
 - Minecraft Version(s): [e.g 1.18, 1.12]
 - Modloader(s): [e.g. Forge]
 - Mod Version: [e.g 1.0]

**Additional context**

**Comment by MommyHeather** [comment]
I see what's happened - the tool checks for the presence of `level.dat` to determine what is and isn't a world. I'll get some more feedback regarding world numbers - to be honest, I hadn't even considered that people would delete world contents before trying to restore. The export option would still create a usable zip, but I do understand why that might not be ideal...

**Comment by MommyHeather** [comment]
As a side note, the filtering exists after someone requested #4 via discord. I'm in favour of keeping it, and it's part of why the export option *does* exist - but I get why that might not be perfect.

**Comment by NielsPilgaard** [comment]
Oh, d'oh 😅 perfectly fine then, I thought I was supposed to delete the contents of the folder first, I may or may not have read some of the manual restore steps and mixed them 😄

**Comment by MommyHeather** [comment]
Haha fair enough

Do you think the instructions are clear enough or do they need adjusting?

**Comment by NielsPilgaard** [comment]
I think they're very verbose to be honest 🤔

**Comment by MommyHeather** [comment]
> I think they're overly verbose to be honest 🤔

Might be the case. I'm not good at explaining, so I wouldn't be surprised... you got any suggestions for an edit?

**Comment by MommyHeather** [comment]
Still not really sure how to improve, but I did make #30 to attempt an improvement haha

**Comment by NielsPilgaard** [comment]
I tried 😅 https://github.com/MommyHeather/AdvancedBackups/pull/31
User-facing documentation is hard...
