### ISSUE TITLE
Feature request : More frequent backups

### ISSUE THREAD

**Issue by imagelesskink** [MommyHeather/AdvancedBackups#35]
**Is your feature request related to a problem? Please describe.**
Differential and Incremental backups (if they worked properly) are extremely disk-efficient and I set up my server to run a full server backup every day (but with only 10 slots), so I'd like to be able to backup more frequently

**Describe the solution you'd like**
Reduce the minimum possible minimum time between updates so I can rollback accidents or griefs without losing too much progress

**Describe alternatives you've considered**
Just reducing the minimum value for the config file should be plenty

**Comment by MommyHeather** [comment]
Hmm. Ideally, for properly low amounts we'd swap the config to minutes, but I'm sure you understand why that's not a good idea haha

Would 15 minutes / 0.25 hours be a good value for you, or are you wanting to go lower?

**Comment by imagelesskink** [comment]
That should be good. There's no good way to express 10 minutes in units of hours

**Comment by MommyHeather** [comment]
[AdvancedBackups-fabric-1.20-3.2-rc1.jar.zip](https://github.com/MommyHeather/AdvancedBackups/files/13060685/AdvancedBackups-fabric-1.20-3.2-rc1.jar.zip)

I won't release this on CF / MR yet, but here's a jar with the change done.

Closing as this is now resolved.
