### ISSUE TITLE
Bug report : 1.19.4 Quilt server crashes after startup

### ISSUE THREAD

**Issue by JadieMae23** [MommyHeather/AdvancedBackups#45]
**Describe the bug**
My 1.19.4 Quilt server crashes right after loading because of a NullPointerException, which it encounters again upon trying to shut down(when the mod's configured to back up on shutdown).

**To Reproduce**
Steps to reproduce the issue:
1. Set up a Quilt server with the installer's GUI exactly as detailed by its download page, then agree to the Minecraft EULA as usual.
2. Add the Quilted Fabric API/Quilt Standard Libraries bundle to the mod folder as the installer asked, along with Advanced Backups.
3. (Optional) In AdvancedBackups.properties, set config.advancedbackups.frequency.shutdown to 'true'.
4. Run the .bat file you created(`java -jar quilt-server-launch.jar nogui`) in the server's root directory again.
5. Wait for the server to load.
6. Immediately after the server finishes and reports load time you should see a crash. In case you followed step 3, you should also see the server fails to stop properly due to the same error.

**Expected behavior**
Normally the server will not show any errors after the "Dedicated server took x seconds to load" message.

**Screenshots**
Without backups on shutdown:
<img width="912" alt="image" src="https://github.com/MommyHeather/AdvancedBackups/assets/57603095/d288126b-4b83-4cd1-9875-7335401a29c5">

With backups on shutdown:
<img width="915" alt="image" src="https://github.com/MommyHeather/AdvancedBackups/assets/57603095/3826b6da-5418-4ace-9faf-6199430b740d">

**Versioning (please complete the following information):**
 - OS: Windows 11 64-bit
 - Java Version: Eclipse Temurin jdk-17.0.8.1+1
 - Minecraft Version(s): 1.19.4
 - Modloader(s): Quilt Server 0.21.1; installer ver. 0.9.1
 - Mod Version: 3.0.1-3.2.1; QFAPI/QSL ver. 6.0.0-beta.11+0.87.0-1.19.4

**Additional context**
I can say with certainty that the mod works just fine for another (Forge 1.18.2)server I'm hosting on the same machine.

**Comment by MommyHeather** [comment]
Confirmed repro on quilt, seems that a fabric modloader method is returning something an invalid value. I'll look to see if there's a way I can do this without yet another branch haha

**Comment by MommyHeather** [comment]
Should have a fix pushed tonight, in theory.

**Comment by MommyHeather** [comment]
[AdvancedBackups-fabric-1.19.3-3.2.2-rc1.zip](https://github.com/MommyHeather/AdvancedBackups/files/13196577/AdvancedBackups-fabric-1.19.3-3.2.2-rc1.zip)

@JadieMae23 could you test this on your end before I see about pushing it to curseforge / modrinth? It's done the job on my end.

**Comment by JadieMae23** [comment]
I can confirm it works on my end as well. Thank you for the swift response!

**Comment by MommyHeather** [comment]
Awesome. I've now checked this on other fabric branches, looks like i'm good to release.
