### ISSUE TITLE
Feature request : enable backup command in single player

### ISSUE THREAD

**Issue by sbenedict** [MommyHeather/AdvancedBackups#47]
Cannot start a manual backup when playing in single player mode.

Enable use of `backup` command from a single player instance without enabling cheats.

**Comment by MommyHeather** [comment]
Sorted and will be available in the next mod update, or [3.4-rc1](https://github.com/MommyHeather/AdvancedBackups/actions/runs/6971771932) when the workflow run finishes - note that this will download a zip, inside that zip will be *another* zip and inside there will be all of the mod jars.
