### ISSUE TITLE
Feature request : remove old backups by date or count

### ISSUE THREAD

**Issue by sbenedict** [MommyHeather/AdvancedBackups#48]
Limiting the backups by total size is not always ideal due to variance in world size. Currently a small 200 MB world could preserve backups 25x that size wasting disk space.

Automatically remove backups after a configured number of days and/or backups.

- Add 'days to keep backups' config setting would specify the number of days of backups to preserve. Delete backups older than this date, except those with dependents.
- Add 'max number of backups' config setting would specify the number of backup files to preserve. If total count of backup files is greater than the specified value, delete oldest backup, except those with dependents.

Other suggestions:

- Change `config.advancedbackups.size` to accept lower than 5 GB would be useful with smaller worlds. And better yet, change it to be a float value, allowing the limit to be set to less than 1 GB.

**Comment by MommyHeather** [comment]
So, I've been thinking about this one.

I'm thinking that we add both of your suggested config values, and then set all three to have a minimum value of 0 - which would then disable the purging for that option altogether.

As an example:
```
config.advancedbackups.purge.size=50
config.advancedbackups.purge.amount=100
config.advancedbackups.purge.days=0
```
This would delete the oldest backup when the total space used reaches 50gb, or when there are more than 100 total backups. Alternatively,

```
config.advancedbackups.purge.size=0
config.advancedbackups.purge.amount=0
config.advancedbackups.purge.days=30
```

This would keep 30 days of backups, and ignore the other two options.


I wanted to grab your opinion before implementing these, given you were the one who made the suggestion - what do you think @sbenedict?

**Comment by sbenedict** [comment]
Sounds like a good solution, exactly as I envisioned!

**Comment by MommyHeather** [comment]
@sbenedict I've got an early run out [here](https://github.com/MommyHeather/AdvancedBackups/actions/runs/7024792066) if you want to test it out - I've got some more testing to do on my end but it should be all fully working.

**Comment by MommyHeather** [comment]
Okay, *now* it's all working, and has been tested on several versions.
Will push this to CF and Modrinth.
