### ISSUE TITLE
Bug report : Backups causing crashes in clients

### ISSUE THREAD

**Issue by imagelesskink** [MommyHeather/AdvancedBackups#49]
**Describe the bug**
When creating a backup, the client will sometimes crash. This message pops up countless times in the log: `[Render thread/WARN]: Unknown custom packet payload: advancedbackups:backup_status`

**To Reproduce**
1. Join the server
2. Make a backup
3. If it doesn't crash, try again

**Expected behavior**
Not crashing

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Whatever Kinetic Hosting uses for their servers
 - Minecraft Version(s): 1.20.2
 - Modloader(s): Fabric
 - Mod Version: 3.4

**Additional context**
It doesn't always cause crashes.

**Comment by MommyHeather** [comment]
Thanks for the report. So far, I've not been able to reproduce it, but I'll be attempting further - do you have a crash report?

**Comment by MommyHeather** [comment]
Okay, I can't reproduce the logspam *or* the crash on seemingly any version - though, I do think I know the fix. I would still like a crash report if you do have one though.

**Comment by imagelesskink** [comment]
[latest.log](https://github.com/MommyHeather/AdvancedBackups/files/13654063/latest.log)

**Comment by MommyHeather** [comment]
Right. This should be totally sorterd with the implementation of the client config in 1.16 - this will be ported to all other versions before release.
