### ISSUE TITLE
[Bug report]: Backup freezes when JVM out of memory

### ISSUE THREAD

**Issue by lexi-the-cute** [MommyHeather/AdvancedBackups#53]
**Describe the bug**

**To Reproduce**
1. Run `/backup snapshot` in game
2. Get message: `Uncaught exception in thread "AB Active Backup Thread"` in console
2.5. Next line is `java.lang.OutOfMemoryError: Required array size too large`
3. World size is 8.7G

**Expected behavior**
Backup to be performed

**Versioning (please complete the following information):**
 - OS: Ubuntu
 - Minecraft Version(s): 1.20.1
 - Modloader(s): Fabric
 - Mod Version: v3.4

**Additional context**
95G available on hard drive

**Comment by MommyHeather** [comment]
Thanks for the report - could you post the config, and the full crash log?

Also, how much memory do you have allocated to the server?

**Comment by lexi-the-cute** [comment]
the server itself doesn't crash. it's just the backup gets stuck running perpetually so i have to restart the server to try again. it would be nice for a cancel backup command. 

i gave the server 12G of RAM out of the 16G total. i also just added 16G of swap to attempt to work around this to no avail. i'm currently trying to see if pausing dynmap's rendering allows the backup to continue (it doesn't)

here's the full error message:
```
[09:10:46] [AB Active Backup Thread/ERROR]: Uncaught exception in thread "AB Active Backup Thread"
java.lang.OutOfMemoryError: Required array size too large
	at java.nio.file.Files.readAllBytes(Files.java:3294) ~[?:?]
	at co.uk.mommyheather.advancedbackups.core.backups.ThreadedBackup.makeZipBackup(ThreadedBackup.java:157) ~[AdvancedBackups-fabric-1.20-3.4.jar:?]
	at co.uk.mommyheather.advancedbackups.core.backups.ThreadedBackup.makeBackup(ThreadedBackup.java:93) ~[AdvancedBackups-fabric-1.20-3.4.jar:?]
	at co.uk.mommyheather.advancedbackups.core.backups.ThreadedBackup.run(ThreadedBackup.java:73) ~[AdvancedBackups-fabric-1.20-3.4.jar:?]
```

i've attached the log file below
[2024-01-01-6.log.gz](https://github.com/MommyHeather/AdvancedBackups/files/13804099/2024-01-01-6.log.gz)

**Comment by MommyHeather** [comment]
Good suggestion with the cancel command, I'll stick it up as a separate feature request.

I've also got a solution for this in the works - just to check, is this a 100% reproduction when running the snapshot command, and does it happen with automatic backups?

**Comment by lexi-the-cute** [comment]
yes, it wants to do a snapshot for the current chain and it's a 100% reproduction with the snapshot command

**Comment by lexi-the-cute** [comment]
when making a manual backup with the tar command, i noticed that i left an older backup file in the world folder from a previous restore. after the manual backup finishes, i'll try again now that i've removed the old backup file

**Comment by MommyHeather** [comment]
Ooh, that extra backup causing this issue certainly would make sense - though this is still something I should be protecting against regardless.

**Comment by lexi-the-cute** [comment]
yep, removing the old backup file allowed the snapshot argument to work again

**Comment by MommyHeather** [comment]
Alright. In that case I'll queue this up for next release as it's not urgent - files large enough to do this are quite an edgecase, and I'll have a release up fairly soon anyway.

**Comment by MommyHeather** [comment]
aand fix fully tested.
