### ISSUE TITLE
Bug report : Backup list is not sorted on Ubuntu/XFCE Terminal

### ISSUE THREAD

**Issue by TheKedart** [MommyHeather/AdvancedBackups#56]
**Describe the bug**
When attempting to do a restore, the list of available backups to restore from is not sorted (appears completely randomized)

**To Reproduce**
1. Run the restore script
2. 1 (From Advanced backups) -> 2 (diff) -> 3 (entire world) -> 2 (server) -> 1 (world)
3. All listed backups are in seemingly random order

**Expected behavior**
Expected the list of backups to be sorted by date in order to easily locate the latest full and differential

**Screenshots**
![Screenshot 2024-01-10 095143](https://github.com/MommyHeather/AdvancedBackups/assets/44425291/6f364774-49ce-43ec-a968-46db506766f9)

[term_output.txt](https://github.com/MommyHeather/AdvancedBackups/files/13891520/term_output.txt)

**Versioning (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS, running on XFCE desktop. App run via XFCE terminal
 - Minecraft Version(s): 1.19
 - Modloader(s): Forge
 - Mod Version: 3.4

**Comment by MommyHeather** [comment]
Fixed in v3.5.
