### ISSUE TITLE
Feature request :  Allow for a shorter period between scheduled backups.

### ISSUE THREAD

**Issue by rodney-mckay1** [MommyHeather/AdvancedBackups#61]
**Is your feature request related to a problem? Please describe.**

The minimum period between backups is 15 minutes. I'm trying to run a incremental backup every 5 minutes.

**Describe the solution you'd like**

Allow for a shorter period between scheduled backups.

**Comment by MommyHeather** [comment]
reopening because the CF workflow is erroring. you can still get jars from [here](https://github.com/MommyHeather/AdvancedBackups/actions/runs/8638865170)
