### ISSUE TITLE
Bug report : Backup failure 

### ISSUE THREAD

**Issue by MuteTiefling** [MommyHeather/AdvancedBackups#68]
**Describe the bug**
Since updating to 3.5, I've been getting this warning that the backup has failed. Logs appear to indicate it's getting stuck on something from Biomancy

**To Reproduce**
1. Seemingly just allowing a backup to trigger with Biomancy installed. 

**Expected behavior**
Backup to complete as before

**Screenshots**
![image](https://github.com/MommyHeather/AdvancedBackups/assets/9543430/a4b8d504-fbbf-4ac0-92ef-8015c4dcf040)

**Versioning (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version(s): 1.20.1
 - Modloader(s): Forge
 - Mod Version: 3.5

**Additional context**
https://gist.github.com/MuteTiefling/cf1e4c6c660c242b27f8ebd1e88ace6d

**Comment by MommyHeather** [comment]
Hmm, and was 3.4 able to make the backup fine with Biomancy installed?

**Comment by MommyHeather** [comment]
Okay. I've been trying to reproduce this, to no avail.

With AB and Biomancy installed only, both scheduled backups and manual backups correctly hash the file and back it up.

Could I have a full modlist please?

**Comment by MuteTiefling** [comment]
Hrm, alright. Wonder if something has gotten corrupt in my world then...

Forced a crash to get a full mod list for you: https://gist.github.com/MuteTiefling/a8af94ab98785a979f06124115582361

**Comment by MommyHeather** [comment]
I'd be surprised if corruption could do it... but perhaps, could you send over your AB config and the `biomancy.spatial.db` from the data directory?

**Comment by MuteTiefling** [comment]
Sure thing. Hope this link works : https://drive.google.com/file/d/1Auz-zvooDFnBi1QdFqEbkmS27S-MibU9/view?usp=drive_link

**Comment by MuteTiefling** [comment]
[ab issue.zip](https://github.com/MommyHeather/AdvancedBackups/files/14970564/ab.issue.zip)

Take two!

**Comment by MommyHeather** [comment]
This is being fixed in multiple ways:

- Add a blacklist for files to not backup 
- Skip a file if it cannot be backed up.
- If any files were skipped, log them in the console / send to a command runner.
- In an upcoming version, toasts will also show the skipped files.
