### ISSUE TITLE
Feature request : Intigration with LuckPerms

### ISSUE THREAD

**Issue by isvein** [MommyHeather/AdvancedBackups#69]
**Is your feature request related to a problem? Please describe.**
I would like to give none-OP users access to use the /backup commands

**Describe the solution you'd like**
Would it be possible to give this mod LuckPerms permition so groups can be given access to /backup command though LuckPerms?

**Describe alternatives you've considered**
Giving other users OP just to use /backup seems like a bad idea :(

**Additional context**

**Comment by MommyHeather** [comment]
Letting any user run the backup command is certainly not something I expected honestly. 

That being said, I'm not acquainted with luckperms but I would've expected it to be able to override a command's permission check without requiring specific integration. Is that not the case?

**Comment by isvein** [comment]
LuckPerms can be used to give users/groups rights to do certain commands that usually is just reserved for OP. Its handy if you got people on your server you want to give certain admin privileges to without giving them full OP.

All I know is that mods need work with certain APIs for LuckPerms to recognise an mod/plugin.
According to its Modrinth page for the Fabric version of LP, "fabric-permissions-api" need to be used: https://github.com/lucko/fabric-permissions-api

**Comment by Jadan1213** [comment]
> **Is your feature request related to a problem? Please describe.** I would like to give none-OP users access to use the /backup commands
> 
> **Describe the solution you'd like** Would it be possible to give this mod LuckPerms permition so groups can be given access to /backup command though LuckPerms?
> 
> **Describe alternatives you've considered** Giving other users OP just to use /backup seems like a bad idea :(
> 
> **Additional context** Add any other context or screenshots about the feature request here.

What is your reasoning for this use case? I'm just curious, as backups are meant to be a set and let run by itself kind of thing, where the only time someone really needs to manually do a backup is if an admin needs to make a potentially breaking change to the server.

**Comment by isvein** [comment]
> > **Is your feature request related to a problem? Please describe.** I would like to give none-OP users access to use the /backup commands
> > **Describe the solution you'd like** Would it be possible to give this mod LuckPerms permition so groups can be given access to /backup command though LuckPerms?
> > **Describe alternatives you've considered** Giving other users OP just to use /backup seems like a bad idea :(
> > **Additional context** Add any other context or screenshots about the feature request here.
> 
> What is your reasoning for this use case? I'm just curious, as backups are meant to be a set and let run by itself kind of thing, where the only time someone really needs to manually do a backup is if an admin needs to make a potentially breaking change to the server.

Here are some reasons I can think of:

-Some people (like me) likes to take an backup before and after builds to document the before and after
-On larger servers, where the admin roles are more split up, not only 1 person or the one who has all the admin rights may be able to take backups when needed out of schedules.

**Comment by MommyHeather** [comment]
Ultimately, I think specifically integrating with another mod isn't really worth it - but what I *can* do is get a config option which adjusts the required permission level, and setting it to `0` would then let everyone run it?

**Comment by Jadan1213** [comment]
I was under the impression all you had to do was add a permission and then all permission mods should be able to utilize it. I don't think allowing everyone to use it is the goal they're seeking.

**Comment by MommyHeather** [comment]
Whilst permission apis do exist, they'd require separate steps for basically every single minecraft version and modloader combination - something that ultimately just isn't going to be viable.

**Comment by isvein** [comment]
Letting everyone run the backup commands would not be a good idea ether :) 
I see this question as answered now :)
