### ISSUE TITLE
Bug report : 

### ISSUE THREAD

**Issue by Yizhouuu** [MommyHeather/AdvancedBackups#72]
**Describe the bug**
real-time schedule does not work
my configuration: 
```
config.advancedbackups.frequency.uptime=false
config.advancedbackups.frequency.schedule=1:00,2:00,3:00,4:00,5:00,6:00,7:00,8:00,9:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,19:00,20:00,21:00,22:00,23:00,24:00
```

the whole config file: 
https://paste.fastmirror.net/?64033f9cfe7a8c5d#14BibagdKxTBpN6wXdydZui41UQDRgj4y8mKA42vGXVu
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/MommyHeather/AdvancedBackups/assets/107225762/1dff4f57-4941-4ce5-b95e-6ecf2fcfc27c)

**Versioning (please complete the following information):**
 - OS: Ubuntu
 - Minecraft Version(s): 1.20.1
 - Modloader(s): Fabric
 - Mod Version: 3.5.1

**Additional context**

**Comment by MommyHeather** [comment]
Seems this bug may have been introduced with either my timer rework or the config rework, I've had a confirmed reproduction and am testing a fix right now.

**Comment by MommyHeather** [comment]
All live on modrinth and awaiting review on curseforge. Also available from https://github.com/MommyHeather/AdvancedBackups/actions/runs/8989631102
