### ISSUE TITLE
Version request : **Fabric 1.20.6**

### ISSUE THREAD

**Issue by Clumsiifi** [MommyHeather/AdvancedBackups#74]
**New Minecraft version :*1.20.6*

**Comment by MommyHeather** [comment]
A jar compatible with fabric 1.20.5 and 1.20.6 is available at https://github.com/MommyHeather/AdvancedBackups/actions/runs/9216316274 (scroll down until you see the artifacts, and grab the fabric 1.20.5 jar)

This will be pushed to Curseforge and Modrinth next release.
