### ISSUE TITLE
Version request : 1.21 (asking if planned)

### ISSUE THREAD

**Issue by HatTrkPatrk** [MommyHeather/AdvancedBackups#75]
Hi, I'm making preparations to setup a 1.21 SMP Fabric server for someone and I'm going through their requested modlist to see if support is planned.

Not asking per se for a release date/timetable but I do want to ask if a 1.21 version of this mod is at least planned. Thank you! (And sorry for being That Guy™ asking about versions lol)

**Comment by MommyHeather** [comment]
Yep, it's planned for Fabric and Neoforge, not yet sure about Forge.

**Comment by MommyHeather** [comment]
totally didn't forget to close this when I released v3.6.
