### ISSUE TITLE
Bug report : Crash after updating neoforge

### ISSUE THREAD

**Issue by MuteTiefling** [MommyHeather/AdvancedBackups#77]
**Describe the bug**
Crash on startup

**Expected behavior**
No crash

**Versioning (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version(s): 1.21
 - Modloader(s): neoforge@21.0.30-beta
 - Mod Version: AdvancedBackups-neoforge-1.21-3.6.1

**Additional context**

[crash-2024-06-23_18.27.04-client.txt](https://github.com/user-attachments/files/15946610/crash-2024-06-23_18.27.04-client.txt)

**Comment by MommyHeather** [comment]
![image](https://github.com/MommyHeather/AdvancedBackups/assets/66441550/69e1d91b-a828-4e52-a470-455d4e9f9070)

Thanks neo.. 21.0.25 removed this from their accesstransformer. I'll have to readd it then, as I need it for sending commands to the server (seems to be the only way to have a clientcommand and servercommand share the same name)

**Comment by MommyHeather** [comment]
Fix has been tested, and will go to CF / MR when the workflow finishes.
